### ISSUE TITLE
Sublevel compatibility

### ISSUE THREAD

**Issue by kumavis** [calvinmetcalf/SQLdown#15]
[sublevel](https://github.com/dominictarr/level-sublevel) breaks when you pass it a sqldown db, because it for some reason it runs `(db.db || db).get`. Sqldown's db.db are Knex instances and dont have `.get()`.

Perhaps this sublevels 'fault', hard to say.

**Comment by calvinmetcalf** [comment]
are you wrapping this in a levelup instance? because I think that's where the db.db comes from

**Comment by kumavis** [comment]
to clarify:
```js
var db = SqlDown('pg://localhost')
db.db //=> knexDb
var subDb = sublevel(db)
subDb.get(key, cb) //=> explode
```
`db.db`:
[level-sublevel](https://github.com/dominictarr/level-sublevel/blob/master/nut.js#L116)
[sqldown](https://github.com/calvinmetcalf/SQLdown/blob/master/index.js#L99)

**Comment by calvinmetcalf** [comment]
I somewhat assumed that Sublevel was meant to work with levelup not leveldown. Aka do 

    levelup('pg://localhost', {db:SqlDown } )


cc @dominictarr

**Comment by kumavis** [comment]
Ah I see. Doing it as you suggest does work for me.
but it also seems to work after the PR without the levelup constructor :cactus: 
either way im satisfied. feel free to close this PR.
