### ISSUE TITLE
valueEncoding: 'binary' doesn't work correctly

### ISSUE THREAD

**Issue by wanderer** [calvinmetcalf/SQLdown#17]
Sqldown doesn't give return the correct value when you `get` using binary encoding. below is a test case

```
var levelup = require('levelup')
var SqlDown = require('sqldown');
var db = levelup('pg://localhost/vapor?table=blockchain', {
  db: SqlDown,
});

var a = new Buffer([1,2,3]);
var b = new Buffer([4,5,6]);

db.put(a, b,{
  keyEncoding: 'binary',
  valueEncoding: 'binary'
}, function(){
  db.get(a, function(err, val){
    console.log("value:" + val);
  })
});
```

the `val` returned is not correct. it should be a `Buffer` but it is instead an object like
```
{data: Array
type: "Buffer"}
```

**Comment by wanderer** [comment]
fixed in PR #18

**Comment by karissa** [comment]
@calvinmetcalf can you review/merge this PR? would love to have binary encodings for [dat](http://github.com/maxogden/dat)

**Comment by calvinmetcalf** [comment]
I believe this was superseded by #22 and should be fixed in master

**Comment by karissa** [comment]
great thanks

**Comment by wanderer** [comment]
since  this is superseded I'll close.
