### ISSUE TITLE
Multiple tables by prefix

### ISSUE THREAD

**Issue by cshum** [calvinmetcalf/SQLdown#28]
A commonly used technique of LevelDB is to segment data by key prefix:

``` js
!users!a1234
!users!foobar
!posts#active!blabla

db.createReadStream({ gt: '!users!', lt: '!users!\xff' }) 
```

The mimics the "table" functionality of SQL database. 

However most SQL databases use Btree while LevelDB uses LSM storage structure. 
The current implementation of SQLdown store key-values into one big table, which is not an ideal scenario for SQL.

In theory it should be possible to split SQLdown storage into multiple tables such as

```
_leveldown_!users!
_leveldown_!users#meta!
_leveldown_!posts!
```

`get()`, `put()`, `del()`, will select table according to the prefix it matches. While `createReadStream()` may join multiple tables accordingly, something like

```
select key, value from "_leveldown_!users!", "_leveldown_!posts!" order by key
```

The implementation is definitely not trivial, just some ideas aligning SQLdown to SQL table storage structure.

**Comment by calvinmetcalf** [comment]
One of the things about the Sublevel method of of prefixing tables is that
it allows you to still access them like a single table so it would be very
non trivial to implement.

That being said a btree is probably just as performant here as well are
only using it for ranges and key lookup. One place we might be able to
improve things could be a combined index on the key and sequence number
